#ifndef __DOCKER_CLI_COMMON_ERROR_INCLUDED_H__
#define __DOCKER_CLI_COMMON_ERROR_INCLUDED_H__

enum _DOCKER_CLI_CODES {
    DOCKERCLIE_OK = 0,
    DOCKERCLIE_CANCELEDINSTALL,
    DOCKERCLIE_DOCKINSTALLED,
    DOCKERCLIE_CANNOTCPIPE,
    DOCKERCLIE_CANNOTIFS,
    DOCKERCLIE_CREATEFOLDER,
    DOCKERCLIE_CANNOTIDOCK,
    DOCKERCLIE_CANNOTINITDAE,
    DOCKERCLIE_CHECKDAESTAT,
    DOCKERCLIE_SYSTEM = 99
};

typedef enum _DOCKER_CLI_CODES DOCKERCLI_CODE;

void docker_cli_error(DOCKERCLI_CODE code);
void win_system_error(const char *msg);

#endif // __DOCKER_CLI_COMMON_ERROR_INCLUDED_H__
