#ifndef __DOCKER_CLI_CONSTANTS_ERROR_CODES_INCLUDED_H__
#define __DOCKER_CLI_CONSTANTS_ERROR_CODES_INCLUDED_H__

enum _ERROR_CODES {
    EDOCKINSTALLED = 1,
    ECANNOTCPIPE = 2,
    ECANNOTIFS = 3,
    ECANNOTIDOCK = 4,
    ECANNOTINITDAE = 5
};

#endif // __DOCKER_CLI_CONSTANTS_ERROR_CODES_INCLUDED_H__
