#ifndef __DOCKER_CLI_GUI_RESOURCES_INCLUDED_H__
#define __DOCKER_CLI_GUI_RESOURCES_INCLUDED_H__

#define IDR_TRAY_POPUPMENU 101
#define IDM_TRAY_OPEN 102
#define IDM_TRAY_OPTIONS 103
#define IDM_TRAY_ABOUT 104
#define IDM_TRAY_EXIT 105

#endif // __DOCKER_CLI_GUI_RESOURCES_INCLUDED_H__
